create extension if not exists pgcrypto;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text default '',created_at timestamptz not null default now());
create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null,owner_id uuid not null references auth.users(id) on delete cascade,plan text not null default 'starter' check(plan in ('starter','growth','enterprise')),created_at timestamptz not null default now());
create table if not exists public.organization_members(organization_id uuid references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text not null default 'annotator' check(role in ('owner','manager','annotator','reviewer')),status text not null default 'active' check(status in ('active','invited','suspended')),created_at timestamptz not null default now(),primary key(organization_id,user_id));
create table if not exists public.projects(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,description text default '',status text not null default 'active' check(status in ('active','paused','completed')),labels jsonb not null default '["person","car","truck","other"]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.batches(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,name text not null,status text not null default 'open' check(status in ('open','in_progress','review','completed')),created_at timestamptz not null default now());
create table if not exists public.images(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,batch_id uuid references public.batches(id) on delete set null,file_name text not null,storage_path text not null,width integer,height integer,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),image_id uuid not null references public.images(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,assignee_id uuid references auth.users(id) on delete set null,reviewer_id uuid references auth.users(id) on delete set null,status text not null default 'unassigned' check(status in ('unassigned','assigned','in_progress','submitted','approved','rejected')),priority integer not null default 2 check(priority between 1 and 5),review_comment text default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.annotations(id uuid primary key default gen_random_uuid(),image_id uuid not null references public.images(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,label text not null,x numeric not null check(x between 0 and 1),y numeric not null check(y between 0 and 1),w numeric not null check(w between 0 and 1),h numeric not null check(h between 0 and 1),confidence numeric check(confidence is null or confidence between 0 and 1),source text not null default 'human' check(source in ('human','ai')),created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.dataset_versions(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,version_number integer not null,format text not null check(format in ('json','csv','yolo','coco')),created_by uuid not null references auth.users(id) on delete cascade,notes text default '',created_at timestamptz not null default now(),unique(project_id,version_number,format));
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.usage_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,event_type text not null,quantity numeric not null default 1,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists projects_org_idx on public.projects(organization_id);create index if not exists batches_project_idx on public.batches(project_id);create index if not exists images_project_idx on public.images(project_id);create index if not exists tasks_project_idx on public.tasks(project_id);create index if not exists anns_image_idx on public.annotations(image_id);create index if not exists audit_org_idx on public.audit_logs(organization_id);create index if not exists usage_org_idx on public.usage_events(organization_id);

create or replace function public.is_org_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organizations where id=org and owner_id=auth.uid()) or exists(select 1 from public.organization_members where organization_id=org and user_id=auth.uid() and status='active'); $$;
create or replace function public.project_org(pid uuid) returns uuid language sql stable security definer set search_path=public as $$ select organization_id from public.projects where id=pid; $$;
create or replace function public.is_project_member(pid uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_org_member(public.project_org(pid)); $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
declare org_id uuid;
begin
 insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing;
 insert into public.organizations(name,owner_id) values(coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'My Workspace')||' Workspace',new.id) returning id into org_id;
 insert into public.organization_members(organization_id,user_id,role) values(org_id,new.id,'owner');
 return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Membership helper view for policy checks
drop view if exists public.project_membership_view;
create view public.project_membership_view with (security_invoker=true) as select p.id project_id,m.user_id,m.role from public.projects p join public.organization_members m on m.organization_id=p.organization_id;

alter table public.profiles enable row level security; alter table public.organizations enable row level security; alter table public.organization_members enable row level security; alter table public.projects enable row level security; alter table public.batches enable row level security; alter table public.images enable row level security; alter table public.tasks enable row level security; alter table public.annotations enable row level security; alter table public.dataset_versions enable row level security; alter table public.audit_logs enable row level security; alter table public.usage_events enable row level security;

drop policy if exists profiles_self on public.profiles; create policy profiles_self on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists org_access on public.organizations; create policy org_access on public.organizations for select to authenticated using(public.is_org_member(id)); create policy org_owner_update on public.organizations for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists org_members_access on public.organization_members; create policy org_members_access on public.organization_members for select to authenticated using(public.is_org_member(organization_id)); create policy org_members_owner_write on public.organization_members for all to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.owner_id=auth.uid())) with check(exists(select 1 from public.organizations o where o.id=organization_id and o.owner_id=auth.uid()));
drop policy if exists project_access on public.projects; create policy project_access on public.projects for select to authenticated using(public.is_org_member(organization_id)); create policy project_owner_write on public.projects for all to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.owner_id=auth.uid())) with check(exists(select 1 from public.organizations o where o.id=organization_id and o.owner_id=auth.uid()));
drop policy if exists batch_access on public.batches; create policy batch_access on public.batches for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id));
drop policy if exists image_access on public.images; create policy image_access on public.images for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id));
drop policy if exists task_access on public.tasks; create policy task_access on public.tasks for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id));
drop policy if exists annotation_access on public.annotations; create policy annotation_access on public.annotations for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id) and created_by=auth.uid());
drop policy if exists versions_access on public.dataset_versions; create policy versions_access on public.dataset_versions for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id) and created_by=auth.uid());
drop policy if exists audit_access on public.audit_logs; create policy audit_access on public.audit_logs for select to authenticated using(public.is_org_member(organization_id)); create policy audit_insert on public.audit_logs for insert to authenticated with check(public.is_org_member(organization_id) and user_id=auth.uid());
drop policy if exists usage_access on public.usage_events; create policy usage_access on public.usage_events for select to authenticated using(public.is_org_member(organization_id)); create policy usage_insert on public.usage_events for insert to authenticated with check(public.is_org_member(organization_id) and user_id=auth.uid());

insert into storage.buckets(id,name,public) values('project-images','project-images',false) on conflict(id) do update set public=false;
drop policy if exists project_images_read on storage.objects; create policy project_images_read on storage.objects for select to authenticated using(bucket_id='project-images' and public.is_project_member((storage.foldername(name))[1]::uuid));
drop policy if exists project_images_write on storage.objects; create policy project_images_write on storage.objects for all to authenticated using(bucket_id='project-images' and public.is_project_member((storage.foldername(name))[1]::uuid)) with check(bucket_id='project-images' and public.is_project_member((storage.foldername(name))[1]::uuid));
